### ISSUE TITLE
Frontend sends PUT request to /api/users/{userId} instead of (...)/avatar on image upload

### ISSUE THREAD

**Issue by Janaza** [LuleaUniversityOfTechnology/2018-project-myfirstline#109]
API & backend could also be updated to remove /api/users/{userId}/avatar and expect the PUT request on /api/users/{userId}

**Comment by JonasHedEng** [comment]
I think `/api/users/{userId}/avatar` is more logical than `/api/avatar` since the avatar is bound to the user. Open for suggestions though.

**Comment by Janaza** [comment]
The backend listens to `/api/users/{userId}/avatar` however the frontend seems to do the PUT request on `/api/users/{userId}` (missing /avatar)

**Comment by JonasHedEng** [comment]
Oh, right! I misread. Well, in that case I'm not sure which is best. The avatar could still be seen as a property of the user and should be under `/api/users/{userId}` but might as well be considered as just "linked" to the user.

In our case, since we do nothing else on `../avatar` I think we could just handle it on `../{userId}`.
